import type { Metadata } from 'next'
import { Instrument_Serif, Inter, Fira_Code } from 'next/font/google'
import SmoothScroll from '@/components/SmoothScroll'
import Nav from '@/components/Nav'
import './globals.css'

const instrumentSerif = Instrument_Serif({
    variable: '--font-instrument-serif',
    weight: ['400'],
    subsets: ['latin'],
})

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
})

const firaCode = Fira_Code({
    variable: '--font-fira-code',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${instrumentSerif.variable} ${inter.variable} ${firaCode.variable} antialiased overflow-x-hidden`}
            >
                <Nav />
                <SmoothScroll>{children}</SmoothScroll>
            </body>
        </html>
    )
}
